name: SkinChanger
version: '1.0'
main: me.blurmit.skin.SkinChanger
api-version: 1.13
authors: [ Blurmit ]
description: Gives players the ability to change their skins
website: blurmit.ml
commands:
  skin:
    description: Gives players the ability to change their skins